### ISSUE TITLE
Not able to remove from favorites in home

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoh88/homebridge-xiaomi-roborock-vacuum#108]
Hey,

I am not able to remove the accessory from my favorites in home.
When I toggle the switch to no it will not disappear and toggled to yes again.

Restarted already the bridge.

**Comment by afharo** [comment]
Hey,

I'm afraid that doesn't look like anything we do in the plugin itself. It looks like an issue in the Home app. 
Personally, I've had some issues in the past in the Home app with me changing some configs and the phone failing to actually set them so they get automatically reverted without any notice.

Never knew why but I've always assumed it is due to sudden failures to sync to iCloud.

**Comment by Phoenix-DH** [comment]
Okay, was not sure ... thats why I am asking.

**Comment by normen** [comment]
I also had one of those, it probably happens since they added "auto grouping" of services per accessory. If you turn that off in the Home App settings you can probably turn off the favorite for every single service (i.e. switch, occupancy sensor etc) and then turn it back on. In my case I was also able to remove the "grouped" device from the favorites on my Mac, but not on the iOS devices.

**Comment by Phoenix-DH** [comment]
I tried and it worked, thanks.
