### ISSUE TITLE
Xiaomi S5Max - Speed was changed to 106%, this speed is not supported

### ISSUE THREAD

**Issue by Itzamna44** [nicoh88/homebridge-xiaomi-roborock-vacuum#110]
Hello.
Please help with this warning in homebridge log.
Thanks.

`[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] INF getFirmware | roborock.vacuum.s5e | Firmwareversion is 3.5.4_0540
[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] STA getDevice | Firmwareversion: 3.5.4_0540
[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] INF changedCleaning | roborock.vacuum.s5e | Cleaning is OFF.
[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] MON changedCharging | roborock.vacuum.s5e | ChargingState is now true
[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] INF changedCharging | roborock.vacuum.s5e | Charging is active
[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 106%
[2/18/2020, 11:01:40 AM] [Xiaomi S5Max] WAR changedSpeed | roborock.vacuum.s5e | Speed was changed to 106%, this speed is not supported
[2/18/2020, 11:02:10 AM] [Xiaomi S5Max] WAR changedSpeed | roborock.vacuum.s5e | Speed was changed to 106%, this speed is not supported`

**Comment by afharo** [comment]
From this comment: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/79#issuecomment-576246934

We have this mapping in the speeds:
And « fan_power »
Soft = 105
Quiet = 101
Balanced = 102
Turbo = 103
Max = 104

But maybe for different firmware versions there are different mappings.
But from that previous issue, it looks like you have the same firmware version and same model 😨 
```
...
[2020-1-13 16:11:18] [Aspirateur] INF getFirmware | roborock.vacuum.s5e | Firmwareversion is 3.5.4_0540
...
```

Can you please confirm what are the different reported speeds (which ones show in the logs when you select a different speed in the app)?

Also asking @infernalK if he's suffering any missing speed? 🤔

**Comment by infernalK** [comment]
Hi, I updated my robot to 3.5.4_0602 and it’s still working well

**Comment by ursusHU** [comment]
Hi,
I have the same issue. The vacuum is actually not running when the message is flooding the log.

[Homebridge] [4/22/2020, 1:34:37 PM] [Roborock S5 Max] INF getCleaning | roborock.vacuum.s5e | Cleaning is false
[Homebridge] [4/22/2020, 1:34:37 PM] [Roborock S5 Max] INF getSpeed | roborock.vacuum.s5e | Fanspeed is 106 over miIO. Converting to HomeKit
[Homebridge] [4/22/2020, 1:34:37 PM] [Roborock S5 Max] INF getBatteryLow | roborock.vacuum.s5e | Batterylevel is 100%
[Homebridge] [4/22/2020, 1:34:41 PM] [Roborock S5 Max] WAR changedSpeed | roborock.vacuum.s5e | Speed was changed to 106%, this speed is not supported

**Comment by ursusHU** [comment]
Checked the logs after the first clean up, now the speed remains on 105, again the vacuum is not running at the time of the log entry was made. So possibly the previous state remains in the status. 106 didn't appeared since the clean up was made.

[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getBattery | roborock.vacuum.s5e | Batterylevel is 100%[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getCharging | roborock.vacuum.s5e | Charging is true (Status is charging)[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getBatteryLow | roborock.vacuum.s5e | Batterylevel is 100%[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getPauseState | roborock.vacuum.s5e | Pause possible is false[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getDocked | roborock.vacuum.s5e | Robot Docked is true (Status is charging)[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getCleaning | roborock.vacuum.s5e | Cleaning is false[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getCleaning | roborock.vacuum.s5e | Cleaning is false[Homebridge] [4/23/2020, 10:41:13 AM] [Roborock S5 Max] INF getCleaning | roborock.vacuum.s5e | Cleaning is false[Homebridge] [4/23/2020, 10:43:25 AM] [Roborock S5 Max] INF getCleaning | roborock.vacuum.s5e | Cleaning is false[Homebridge] [4/23/2020, 10:43:25 AM] [Roborock S5 Max] INF getSpeed | roborock.vacuum.s5e | Fanspeed is 105 over miIO. Converting to HomeKit[Homebridge] [4/23/2020, 10:43:25 AM] [Roborock S5 Max] INF getSpeed | roborock.vacuum.s5e | Fanspeed is 105 over miIO "Soft" > HomeKit speed 15%

**Comment by afharo** [comment]
> Speed was changed to 106%, this speed is not supported

What is the mode/speed you had enabled in the Xiaomi Mi app when this occurred?

**Comment by ursusHU** [comment]
Ok I found it! :) usually I run full clean ups every day, with different room suction level. Mostly balanced, but in one room I have turbo.
As soon as I turn on the Customize setting in the app I get the 106. in the logs.

![xiaomi](https://user-images.githubusercontent.com/61931127/80260476-4afd2600-8688-11ea-8e9b-ac00ccbde523.jpg)

**Comment by afharo** [comment]
Cool! So 106 means turbo?
Unfortunately, I don't have that model to test it locally and I'm puzzled @infernalK confirmed it's working for him (he owns that model).

@ursusHU can you try modifying the file https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/models/speedmodes.js#L43-L56 locally with different mappings to find out which one works for you?

**Comment by ursusHU** [comment]
No, it seems it means customized room suction. In this case the previously set suction levels used for each room separately, not a global one. 
Gentle - 105
Silent - 101
Balanced - 102
Turbo - 103
Max - 104
So this corresponds to the mappings you already use. And if I select the above mentioned customized room suction control.

Customized - 106

[Homebridge] [4/25/2020, 9:28:41 AM] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 105%[Homebridge] [4/25/2020, 9:28:41 AM] [Roborock S5 Max] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 105% (Soft), for HomeKit 15%[Homebridge] [4/25/2020, 9:29:41 AM] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 101%[Homebridge] [4/25/2020, 9:29:41 AM] [Roborock S5 Max] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 101% (Quiet), for HomeKit 38%[Homebridge] [4/25/2020, 9:30:11 AM] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 102%[Homebridge] [4/25/2020, 9:30:11 AM] [Roborock S5 Max] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 102% (Balanced), for HomeKit 60%[Homebridge] [4/25/2020, 9:30:41 AM] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 103%[Homebridge] [4/25/2020, 9:30:41 AM] [Roborock S5 Max] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 103% (Turbo), for HomeKit 77%[Homebridge] [4/25/2020, 9:31:11 AM] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 104%[Homebridge] [4/25/2020, 9:31:11 AM] [Roborock S5 Max] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 104% (Max), for HomeKit 100%[Homebridge] [4/25/2020, 9:32:11 AM] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 106%[Homebridge] [4/25/2020, 9:32:11 AM] [Roborock S5 Max] WAR changedSpeed | roborock.vacuum.s5e | Speed was changed to 106%, this speed is not supported

**Comment by infernalK** [comment]
Hi, 
Yes 106 seems to be customized/auto mode : 


https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/custom_mode.md#extended-modes

**Comment by afharo** [comment]
Oh! Good to know! Thanks for confirming!
What do you think it would be the right call in this situation? Represent this as max? As 0? 
Do not change the speed but log it’s custom?
Or let it fail as it is now?

**Comment by infernalK** [comment]
I don’t know how to call it but it seems to represent a preset speed for room cleaning and it can be any speed.
I don’t use this function cause I use the robot to clean just one room.
I think it could be a good idea to log it just to avoid error.

**Comment by ursusHU** [comment]
Would it be possible to include a
switch, which turns on the customized room cleaning? I think it is a good feature, also mopping can be controlled this way.

**Comment by afharo** [comment]
If I understood correctly, the `customized` cleaning is reported as 106, but it can be anything the user has selected in the app? And there may be multiple `custom` cleanings? If so, I don't think there is any way to select that `custom` speed: because it will result in mode 106, but homebridge doesn't know anything else on top of that, does it?
Am I missing anything?

If setting it to 106 is enough to enable the `customized` cleaning, we can add it as part of the [speed selector](https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/models/speedmodes.js#L43-L56). And you can create a Scene that triggers the Room cleaning (from the [room cleaning feature](https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum#semi-automatic) and sets the speed to the mode `106`. But again, this is only valid if 106 is mapped to only 1 custom cleaning setup, not any custom cleaning setup.

**Comment by ursusHU** [comment]
Yes. Basically you are able to setup different vacuum speed, and mopping for each room. There are no custom cleanings, but a “switch” to take the predefined vacuum speeds for the rooms. I will check if this value differs if you select only room cleaning or full cleaning. 
HomeKit would only set if the robot needs to use the predefined speeds or the speed selected in HomeKit via the slider. The room selection is not included, I assume if you set the speed to 106, the. The robot will use the settings from its own app or? Then you select room or full cleaning.

**Comment by afharo** [comment]
So there are 2 things here:

1. Speed: Cleaning modes: turbo, balanced, quiet, ...
2. Type of cleaning: Full cleaning, zone cleaning, room cleaning.

Homekit is super extensive and useful, but, unfortunately, the Home app UI covers a very limited amount of its capabilities. iOS 13's Home app just happens to merge the ON/OFF (Full cleaning) toggle and the Speed slider (I guess for UI design reasons). When it's OFF, the Home app shows it like if the speed is 0, but the Robot actually reports it's not cleaning but keeps the last used cleaning speed (and you can see so in the logs) because it didn't actually change.

This is easier seen in the Eve app (where it reports each indicator individually). In that app you can create a scene that sets the speed to your like and enables the cleaning for a specific room. That scene is then fully compatible and usable in the Home app :)

**Comment by afharo** [comment]
we can test it :)
Just change the file `models/speedmodes.js` in your installation to include the 106 use case when the speed dial is set to a certain speed (say '10%'?)
```
    // 1-10%   = "Custom"
    { homekitTopLevel: 10, miLevel: 106, name: "Custom" },
```
and restart the homebridge server.

Then give it a try to find out if the robot is smart enough to know what Custom means :)

**Comment by ursusHU** [comment]
It works!
