### ISSUE TITLE
Permission denied Install

### ISSUE THREAD

**Issue by ebrger** [nicoh88/homebridge-xiaomi-roborock-vacuum#147]
I cannot install the plugin that reports log messages. I can install other plugins without problems:

USER: homebridge
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-xiaomi-roborock-vacuum@latest

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoh88/miio.git /home/homebridge/.npm/_cacache/tmp/git-clone-3d3b67a5
npm ERR! /home/homebridge/.npm/_cacache/tmp/git-clone-3d3b67a5/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-04-09T10_21_55_411Z-debug.log

**Comment by abaskakau** [comment]
You can try interactive user mode
Type `sudo su -`
Then type `npm install -g homebridge-xiaomi-roborock-vacuum@latest --unsafe-perm`

**Comment by afharo** [comment]
@nicoh88 we have lots of opened issues because of failing to install from git. 
How about publishing our version of the `miio` library under a different name? Maybe `@nicoh88/miio` or `miio-nicoh88`?

I believe this will help with:

1. Solving the `git` issues (no more installations based on git, unless we are installing a test version)
2. It will make clear we are running a different `miio` library than the (no-longer-maintained) original.

**Comment by ebrger** [comment]
Thank for Support!
I solved it myself.  The problem went away after I updated NPM.

**Comment by nicoh88** [comment]
e318d7b2c217f7383eca98d0e903f1e2bd6be23b
