### ISSUE TITLE
iOS13.1.2 T6 Fan Speed over 100% shows not supported, and T6 cleaner can only be normal speed

### ISSUE THREAD

**Issue by elfive1992** [nicoh88/homebridge-xiaomi-roborock-vacuum#69]

**Comment by elfive1992** [comment]
logs:
[10/10/2019, 9:45:46 AM] [RockRoboT6] MON changedSpeed | roborock.vacuum.t6 | FanSpeed is now 102%
[10/10/2019, 9:45:46 AM] [RockRoboT6] WAR changedSpeed | roborock.vacuum.t6 | Speed was changed to 102%, this speed is not supported

**Comment by afharo** [comment]
Hi @elfive1992,
What is the speed mode you have on your vacuum when you see this 102%?

**Comment by elfive1992** [comment]
@afharo in iOS Mi Home App, it shows standard fan speed level. (silent, standard, medium, turbo)

**Comment by afharo** [comment]
It looks to me like your t6 is using the 3rd gen speed mapping: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/index.js#L64

But since we don’t have that model in our list yet: https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/blob/master/index.js#L23
It is using the default gen1 mapping and failing.
I’m away from my keyboard now but, can you please create a PR with an addition mapping the t6 model to the gen3?
If you can’t do it, I think I’ll be able to change it this weekend

**Comment by elfive1992** [comment]
Thank you @afharo ,
I will try to create a PR.
and also Thank you for your reply.

**Comment by elfive1992** [comment]
I've created a PR:[https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/pull/70](#70 )
it turns out not a fanSpeed map issue, but a missing vacuum mode(roborock.vacuum.t6) issue.

**Comment by nicoh88** [comment]
Thanks @elfive1992 
Merged, new NPM Version published.

**Comment by elfive1992** [comment]
@nicoh88 appreciate and also thank you.
btw,may I ask why we can't support nodeJS version 8.16.1 or nodeJS version 8.x.x ?

I'm running homebridge in my openWrt/LEDE router, which only support nodeJS up to version 8.16.1.
and for some unknown reason, homebridge in docker isn't work for me(can't add to home assisstant App, but runs OK).

**Comment by afharo** [comment]
Hi @elfive1992,
It was actually me who raised that limitation. I developed it on Node 10.

Checking on https://node.green/ about the ES features we use in the implementation (classes, async/await and object destructuring), node 8 might be supported.
