### ISSUE TITLE
Care indicators showing 0,0% (Xiaomi Roborock S5)

### ISSUE THREAD

**Issue by frossmant** [nicoh88/homebridge-xiaomi-roborock-vacuum#83]
After a lot of troubleshooting in order to get the correct TOKEN after an accidental firmware upgrade upon installation I've got the damn thing to work.

The plugin all works fine turning on / off and setting the speed of the Xiaomi Roborock S5.

However all the "care indicators" showing battery, filter, brush and sensor status are always showing 0,0%.

Is this a bug ? Or does this feature only support specific models of Roborocks ?

Regards

**Comment by afharo** [comment]
I’ve got the S5 and it’s working for me:
![A7F7033B-6EA8-4423-85F7-D12BFCFEA596](https://user-images.githubusercontent.com/5469006/72649691-3ff27580-3976-11ea-844b-e16ed9234ab2.png)

The only thing is that I need to use the app Eve instead of Home to see it. I think those indicators are not currently supported by the “official” app itself.

**Comment by frossmant** [comment]
![42F3296D-5821-4797-BF0D-E5D31A3DD79F](https://user-images.githubusercontent.com/16928591/72649847-06723800-397f-11ea-842f-bb659b2064c7.png)

Strange. This is how it looks for me. 

Are you on the latest firmware ?

**Comment by afharo** [comment]
How old is your robot?
0% is brand new.
>100% you need to change apply some care.
Anyway, since you asked:
Firmware: 3.3.9_001886

**Comment by frossmant** [comment]
Ah my mistake then, I thought 100% meant fresh and healthy and not counting the other way around.

Then it's no problem :) Thanks for the clarification, i'l close this "issue" then :)
